<dumpable> ::= "Examples"
<char> ::= [a-z] | [A-Z]
<string> ::= <char>+ (" " <char>+)*
<nonZeroDigit> ::= [1-9]
<digit> ::= "0" | <nonZeroDigit>
<integer> ::= "0" | <nonZeroDigit> <digit>*
<calories> ::= <integer>
<dishName> ::= "\"" <string> "\""

<dish> ::= "Dish " <dishName> " " <calories>
         | "BigDish (" <dish> ") (" <dish> ")"

<command> ::= "Dump " <dumpable>
            | "CreateDish (" <dish> ")"
            | "RemoveDish " <dishName>
            | "EatDish (" <dish> ")"